### ISSUE TITLE
Issue using custom EE environnement

### ISSUE THREAD

**Issue by mehdia4ever** [kurokobo/awx-on-k3s#215]
## Environment

- OS: Red Hat Enterprise Linux release 8.6
- Docker version 23.0.1, build a5ee5b1

## Description
Issue using my custom EE 

## Step to Reproduce
building my custom EE with execution execution-environment.yml
---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.12-latest'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c"
ansible_config: 'ansible.cfg'

additional_build_steps:
  prepend:
...

## Logs

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 438, in _run_internal
    lines = resultfile.readlines()
OSError: read() should have returned a bytes object, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 604, in run
    res = receptor_job.run()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 320, in run
    res = self._run_internal(receptor_ctl)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/receptor.py", line 447, in _run_internal
    raise RuntimeError(detail)
RuntimeError: exit status 1

**Comment by mehdia4ever** [comment]
edit: i also have the same problem using the official awx ee quay.io/ansible/awx-ee:latest

**Comment by kurokobo** [comment]
Could you please provide more details about steps to reproduce?
How and where did you get that error?
I want to try to reproduce your error but I can't understand how should I do that.

**Comment by mehdia4ever** [comment]
Am using AWX v22 on Docker architecture.

![image](https://github.com/kurokobo/awx-on-k3s/assets/73796056/ae9b16c1-4ed1-48c2-8e3f-11accbc0947f)


![image](https://github.com/kurokobo/awx-on-k3s/assets/73796056/8d5d0882-2b08-405f-8673-a566ed70cfd7)

I have this error when am refreshing my project.

![image](https://github.com/kurokobo/awx-on-k3s/assets/73796056/4c5f62c7-0aeb-47f4-afce-094219eeba5e)

**Comment by kurokobo** [comment]
@mehdia4ever 
Sorry to say this but Docker-based deployment is completely out-of-scope of my repository.
Updating projects is invoked inside the `awx-task` container and is not related to EE, so your issue might be caused by your deployment. I've never be faced that error and I still don't know how you've deployed AWX on Docker so I don't have any idea about your issue.
If you have same issue on K8s-based deployment as described in my guide, it's welcome to fill new issue here, but if not, you should post your issue on the official community; mailing list, or chat (or if you think this is a bug, fill the issue on the AWX's repository): https://github.com/ansible/awx#get-involved
